from os import system

lib_list = ['libopencv_calib3d.2.4.13.dylib','libopencv_ml.2.4.13.dylib','libopencv_calib3d.2.4.dylib','libopencv_ml.2.4.dylib','libopencv_calib3d.dylib','libopencv_ml.dylib','libopencv_contrib.2.4.13.dylib','libopencv_nonfree.2.4.13.dylib','libopencv_contrib.2.4.dylib','libopencv_nonfree.2.4.dylib','libopencv_contrib.dylib','libopencv_nonfree.dylib','libopencv_core.2.4.13.dylib','libopencv_objdetect.2.4.13.dylib','libopencv_core.2.4.dylib','libopencv_objdetect.2.4.dylib','libopencv_core.dylib','libopencv_objdetect.dylib','libopencv_features2d.2.4.13.dylib','libopencv_ocl.2.4.13.dylib','libopencv_features2d.2.4.dylib','libopencv_ocl.2.4.dylib','libopencv_features2d.dylib','libopencv_ocl.dylib','libopencv_flann.2.4.13.dylib','libopencv_photo.2.4.13.dylib','libopencv_flann.2.4.dylib','libopencv_photo.2.4.dylib','libopencv_flann.dylib','libopencv_photo.dylib','libopencv_gpu.2.4.13.dylib','libopencv_stitching.2.4.13.dylib','libopencv_gpu.2.4.dylib','libopencv_stitching.2.4.dylib','libopencv_gpu.dylib','libopencv_stitching.dylib','libopencv_highgui.2.4.13.dylib','libopencv_superres.2.4.13.dylib','libopencv_highgui.2.4.dylib','libopencv_superres.2.4.dylib','libopencv_highgui.dylib','libopencv_superres.dylib','libopencv_imgproc.2.4.13.dylib','libopencv_video.2.4.13.dylib','libopencv_imgproc.2.4.dylib','libopencv_video.2.4.dylib','libopencv_imgproc.dylib','libopencv_video.dylib','libopencv_legacy.2.4.13.dylib','libopencv_videostab.2.4.13.dylib','libopencv_legacy.2.4.dylib','libopencv_videostab.2.4.dylib','libopencv_legacy.dylib','libopencv_videostab.dylib']
libs_list = ['/usr/local/lib/python2.7/site-packages/cv2.so','/usr/local/lib/libopencv_calib3d.2.4.13.dylib','/usr/local/lib/libopencv_ml.2.4.13.dylib','/usr/local/lib/libopencv_calib3d.2.4.dylib','/usr/local/lib/libopencv_ml.2.4.dylib','/usr/local/lib/libopencv_calib3d.dylib','/usr/local/lib/libopencv_ml.dylib','/usr/local/lib/libopencv_contrib.2.4.13.dylib','/usr/local/lib/libopencv_nonfree.2.4.13.dylib','/usr/local/lib/libopencv_contrib.2.4.dylib','/usr/local/lib/libopencv_nonfree.2.4.dylib','/usr/local/lib/libopencv_contrib.dylib','/usr/local/lib/libopencv_nonfree.dylib','/usr/local/lib/libopencv_core.2.4.13.dylib','/usr/local/lib/libopencv_objdetect.2.4.13.dylib','/usr/local/lib/libopencv_core.2.4.dylib','/usr/local/lib/libopencv_objdetect.2.4.dylib','/usr/local/lib/libopencv_core.dylib','/usr/local/lib/libopencv_objdetect.dylib','/usr/local/lib/libopencv_features2d.2.4.13.dylib','/usr/local/lib/libopencv_ocl.2.4.13.dylib','/usr/local/lib/libopencv_features2d.2.4.dylib','/usr/local/lib/libopencv_ocl.2.4.dylib','/usr/local/lib/libopencv_features2d.dylib','/usr/local/lib/libopencv_ocl.dylib','/usr/local/lib/libopencv_flann.2.4.13.dylib','/usr/local/lib/libopencv_photo.2.4.13.dylib','/usr/local/lib/libopencv_flann.2.4.dylib','/usr/local/lib/libopencv_photo.2.4.dylib','/usr/local/lib/libopencv_flann.dylib','/usr/local/lib/libopencv_photo.dylib','/usr/local/lib/libopencv_gpu.2.4.13.dylib','/usr/local/lib/libopencv_stitching.2.4.13.dylib','/usr/local/lib/libopencv_gpu.2.4.dylib','/usr/local/lib/libopencv_stitching.2.4.dylib','/usr/local/lib/libopencv_gpu.dylib','/usr/local/lib/libopencv_stitching.dylib','/usr/local/lib/libopencv_highgui.2.4.13.dylib','/usr/local/lib/libopencv_superres.2.4.13.dylib','/usr/local/lib/libopencv_highgui.2.4.dylib','/usr/local/lib/libopencv_superres.2.4.dylib','/usr/local/lib/libopencv_highgui.dylib','/usr/local/lib/libopencv_superres.dylib','/usr/local/lib/libopencv_imgproc.2.4.13.dylib','/usr/local/lib/libopencv_video.2.4.13.dylib','/usr/local/lib/libopencv_imgproc.2.4.dylib','/usr/local/lib/libopencv_video.2.4.dylib','/usr/local/lib/libopencv_imgproc.dylib','/usr/local/lib/libopencv_video.dylib','/usr/local/lib/libopencv_legacy.2.4.13.dylib','/usr/local/lib/libopencv_videostab.2.4.13.dylib','/usr/local/lib/libopencv_legacy.2.4.dylib','/usr/local/lib/libopencv_videostab.2.4.dylib','/usr/local/lib/libopencv_legacy.dylib','/usr/local/lib/libopencv_videostab.dylib']
cmd = 'sudo install_name_tool -change '
path = '/usr/local/lib/'

for item in lib_list:
	for lib in libs_list:
		system(cmd + item + ' ' + path + item + ' ' + lib)
